name: Cargo build & test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLORS: always

permissions:
  contents: read

jobs:
  build_and_test:
    name: charm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v6
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo clippy --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
